apiVersion: v1
kind: Service
metadata:
  name: dockerse-deployment
spec:
  type: NodePort
  selector:
    app: dockerse-deployment
  ports:
  - protocol: "TCP" 
    port: 8110
    targetPort: 8110